/** THIS FILE IS AUTOGENERATED! DO NOT MODIFY! */
import { IconProps } from '@ux-aspects-universal/react/icon';
import * as React from 'react';
export declare const DocumentOpenWordIcon: React.ForwardRefExoticComponent<Omit<IconProps, "ref"> & React.RefAttributes<SVGSVGElement>>;
